# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b438924c-b7df-4e04-959b-0295b1a8b628";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b438924c-b7df-4e04-959b-0295b1a8b628".device = "/dev/disk/by-uuid/b438924c-b7df-4e04-959b-0295b1a8b628";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3765-5041";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f5f58324-c183-4b16-9486-4e1a09d5d43d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
